In [69]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tslearn.utils import to_time_series
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from datetime import datetime

In [70]:
data = pd.read_csv('jaguar_movement_data.csv',parse_dates=True,usecols=[1,2,3,6])

In [71]:
def date_to_num(d):
    return datetime.strptime(d, "%m/%d/%y %H:%M").timestamp()

data['timestamp'] = data['timestamp'].apply(date_to_num)
print(data.head())

      timestamp  location.long  location.lat  individual.local.identifier (ID)
0  1.276635e+09     -58.030128    -23.326947                                 1
1  1.276650e+09     -58.030643    -23.328427                                 1
2  1.276721e+09     -58.030472    -23.327311                                 1
3  1.276786e+09     -58.027983    -23.309952                                 1
4  1.276800e+09     -58.027747    -23.310006                                 1


In [86]:
# X = np.array((11,3,150))
# for i in range(1,12):
#     data_i = data[data['individual.local.identifier (ID)'] == i]
#     data_i.pop('individual.local.identifier (ID)')
#     X[i] = (data_i.values[:150])

ValueError: setting an array element with a sequence.

In [93]:
#X= np.array(X)
print(data.values)
X = data.values
np.random.shuffle(X)
print(X)

[[ 1.27663458e+09 -5.80301280e+01 -2.33269470e+01  1.00000000e+00]
 [ 1.27664952e+09 -5.80306430e+01 -2.33284270e+01  1.00000000e+00]
 [ 1.27672056e+09 -5.80304720e+01 -2.33273110e+01  1.00000000e+00]
 ...
 [ 1.45548720e+09 -5.74887661e+01 -1.69011144e+01  1.17000000e+02]
 [ 1.45549080e+09 -5.74770372e+01 -1.68988467e+01  1.17000000e+02]
 [ 1.45549440e+09 -5.74846269e+01 -1.69078125e+01  1.17000000e+02]]
[[ 1.38382566e+09 -5.62345431e+01 -2.00437581e+01  1.50000000e+01]
 [ 1.21721400e+09 -5.70433635e+01 -1.95426877e+01  1.05000000e+02]
 [ 1.42028640e+09 -5.73923319e+01 -1.69247361e+01  8.10000000e+01]
 ...
 [ 1.40981400e+09 -5.80249590e+01 -2.33099670e+01  9.00000000e+00]
 [ 1.45328040e+09 -5.74721681e+01 -1.68972789e+01  1.17000000e+02]
 [ 1.38712692e+09 -5.75033081e+01 -1.68685425e+01  8.10000000e+01]]


In [94]:
km = KMeans(n_clusters=2, max_iter=10)
km.fit(X[0:1000])

KMeans(max_iter=10, n_clusters=2)

In [95]:
print(km.predict(X[2000]))

ValueError: Expected 2D array, got 1D array instead:
array=[ 1.15012086e+09 -5.82232810e+01 -1.99718760e+01  7.50000000e+01].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.